name: Docker Image CI

on:
  push:
    branches: [ vue3 ]
  pull_request:
    branches: [ vue3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run build
    - name: Docker Repository Configuration
      uses: macbre/push-to-ghcr@master
      with:
        image_name: vasilebujor/iais-frontend
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
