name: Docker Image CI

on:
  push:
    branches: [ vue3 ]
  pull_request:
    branches: [ vue3 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    #- run: npm install
    - name: Install dependencies clean
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install --legacy-peer-deps
    - run: npm run build
    - name: Docker Repository Configuration
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
